export const Userdata = [
  {
    id: 1,
    fullname: "Peter Francis Robante",
    email: "robantepeterfran@gmail.com",
    status: "active",
    department: "College of Information Technology and Computing",
    position: "Student",
    password: "KD129SDLDF@$DDLSD?^DF#",
    type: "Super Admin",
  },
  {
    id: 2,
    fullname: "Elon Musk",
    email: "elon.musk123@gmail.com",
    status: "active",
    department: "College of Information Technology and Computing",
    position: "Teacher",
    password: "KD129SDLDF@$DDLSD?^DF#",
    type: "Admin",
  },
  {
    id: 3,
    fullname: "Steve Job",
    email: "job_steve.24@gmail.com",
    status: "active",
    department: "College of Engineering And Architecture",
    position: "Teacher",
    password: "KD129SDLDF@$DDLSD?^DF#",
    type: "Admin",
  },
  {
    id: 4,
    fullname: "Cliffkhan Gamayon",
    email: "gamayon.cliffkhan@gmail.com",
    status: "active",
    department: "College of Information Technology and Computing",
    position: "Student",
    password: "KD129SDLDF@$DDLSD?^DF#",
    type: "User",
  },

  {
    id: 5,
    fullname: "Clint Egargo",
    email: "Clint.Egargo@gmail.com",
    status: "inactive",
    department: "College of Information Technology and Computing",
    position: "Student",
    password: "KD129SDLDF@$DDLSD?^DF#",
    type: "User",
  },
  {
    id: 6,
    fullname: "John Doe",
    email: "john.doe@example.com",
    status: "inactive",
    department: "College of Science and Mathematics",
    position: "Teacher",
    password: "z9K$72Ls#DWz",
    type: "User",
  },
  {
    id: 7,
    fullname: "Jane Smith",
    email: "jane.smith@example.com",
    status: "inactive",
    department: "College of Science and Technology Education",
    position: "Student",
    password: "5d9v@P$Fs7!Y",
    type: "User",
  },
  {
    id: 8,
    fullname: "Michael Johnson",
    email: "michael.johnson@example.com",
    status: "active",
    department: "College of Technology",
    position: "Teacher",
    password: "Pv6!s2Z@2Xw",
    type: "User",
  },
  {
    id: 9,
    fullname: "Emily Davis",
    email: "emily.davis@example.com",
    status: "active",
    department: "College of Science and Mathematics",
    position: "Student",
    password: "7#HzP$6Fp28Y",
    type: "User",
  },
  {
    id: 10,
    fullname: "David Wilson",
    email: "david.wilson@example.com",
    status: "inactive",
    department: "College of Science and Mathematics",
    position: "Student",
    password: "dfLZ@58sm!F3",
    type: "User",
  },
  {
    id: 11,
    fullname: "Sarah Thompson",
    email: "sarah.thompson@example.com",
    status: "active",
    department: "College of Science and Technology Education",
    position: "Student",
    password: "2V#9$aXp7ZS4",
    type: "User",
  },
  {
    id: 12,
    fullname: "Christopher Martinez",
    email: "christopher.martinez@example.com",
    status: "active",
    department: "College of Engineering And Architecture",
    position: "Student",
    password: "Xx9#G5d@2FD!",
    type: "User",
  },

  {
    id: 13,
    fullname: "Jessica Anderson",
    email: "jessica.anderson@example.com",
    status: "active",
    department: "College of Engineering And Architecture",
    position: "Student",
    password: "v7Y!Dx$L#5Gz",
    type: "User",
  },
  {
    id: 14,
    fullname: "Matthew Taylor",
    email: "matthew.taylor@example.com",
    status: "active",
    department: "College of Science and Mathematics",
    position: "Teacher",
    password: "P$X@6v2y!G4b",
    type: "User",
  },
  {
    id: 15,
    fullname: "Ashley Moore",
    email: "ashley.moore@example.com",
    status: "active",
    department: "College of Science and Technology Education",
    position: "Student",
    password: "zSb#Xv$6G32@",
    type: "User",
  },
  {
    id: 16,
    fullname: "Daniel Lee",
    email: "daniel.lee@example.com",
    status: "active",
    department: "College of Information Technology and Computing",
    position: "Student",
    password: "5Gv@#8LD2!xy",
    type: "User",
  },
  {
    id: 17,
    fullname: "Olivia Clark",
    email: "olivia.clark@example.com",
    status: "active",
    department: "College of Information Technology and Computing",
    position: "Student",
    password: "7zJ3#SL",
    type: "User",
  },
  {
    id: 18,
    fullname: "William Rodriguez",
    email: "william.rodriguez@example.com",
    status: "active",
    department: "College of Science and Technology Education",
    position: "Student",
    password: "9P!Xz#L2bF7D",
    type: "User",
  },

  {
    id: 19,
    fullname: "Sophia Walker",
    email: "sophia.walker@example.com",
    status: "active",
    department: "College of Engineering And Architecture",
    position: "Student",
    password: "6S!9L#Xb5JzD",
    type: "User",
  },

  {
    id: 20,
    fullname: "James Anderson",
    email: "james.anderson@example.com",
    status: "inactive",
    department: "College of Engineering And Architecture",
    position: "Student",
    password: "z3#bJ9F8x!Vd",
    type: "User",
  },

  {
    id: 21,
    fullname: "Mia Thomas",
    email: "mia.thomas@example.com",
    status: "active",
    department: "College of Technology",
    position: "Student",
    password: "4Ld7#zXb!9Fs",
    type: "User",
  },

  {
    id: 22,
    fullname: "Benjamin Turner",
    email: "benjamin.turner@example.com",
    status: "inactive",
    department: "College of Engineering And Architecture",
    position: "Student",
    password: "Lx2b!9Fz7J#D",
    type: "User",
  },

  {
    id: 23,
    fullname: "Ava Garcia",
    email: "ava.garcia@example.com",
    status: "active",
    department: "College of Technology",
    position: "Teacher",
    password: "9F7Xb!2Dz#LJ",
    type: "User",
  },

  {
    id: 24,
    fullname: "Alexander Carter",
    email: "alexander.carter@example.com",
    status: "active",
    department: "College of Technology",
    position: "Student",
    password: "bD#2FzL9J!7X",
    type: "User",
  },

  {
    id: 25,
    fullname: "Charlotte Hall",
    email: "charlotte.hall@example.com",
    status: "active",
    department: "College of Technology",
    position: "Student",
    password: "b!2J7Xz9D#LF",
    type: "User",
  },
  {
    id: 26,
    fullname: "Nelthon Pacudan",
    email: "pacudan.nelthon@gmail.com",
    status: "active",
    department: "College of Information Technology and Computing",
    position: "Student",
    password: "KD129SDLDF@$DDLSD?^DF#",
    type: "User",
  },
   {
    id: 27,
    fullname: "Mr PotatoParty",
    email: "potata.partay@yahoo.com",
    status: "active",
    department: "College of Engineering and Architecture",
    position: "Teacher",
    password: "KD129SDLDF@$DDLSD?^DF#",
    type: "User",
  },
   {
    id: 28,
    fullname: "Andava NSFW",
    email: "andava@gmail.com",
    status: "active",
    department: "College of Information Technology and Computing",
    position: "Teacher",
    password: "KD129SDLDF@$DDLSD?^DF#",
    type: "User",
  },
  {
    id: 29,
    fullname: "Pumpkin Sinclair",
    email: "pumps.NSFW.1999@newgrounds.com",
    status: "active",
    department: "College of Information Technology and Computing",
    position: "Student",
    password: "KD129SDLDF@$DDLSD?^DF#",
    type: "User",
  },
  {
    id: 30,
    fullname: "Mal Contentus",
    email: "malco.18@gmail.com",
    status: "inactive",
    department: "College of Information Technology and Computing",
    position: "Student",
    password: "KD129SDLDF@$DDLSD?^DF#",
    type: "User",
  },
  {
    id: 31,
    fullname: "Mong Mong Narcos",
    email: "necropolitics.enjoyer77@lgu.gov",
    status: "inactive",
    department: "College of Information Technology and Computing",
    position: "Teacher",
    password: "KD129SDLDF@$DDLSD?^DF#",
    type: "User",
  },
];
